### ISSUE TITLE
These Approval - missing Deny/Approve

### ISSUE THREAD

**Issue by dvolavko** [frantisekz/redhat-research#12]
Does not work, even after adding /beta/.
These -->Thesis

![thesis approval](https://user-images.githubusercontent.com/30719674/30738900-d7ec55e0-9f8b-11e7-9fb0-aff75613fe93.png)

**Comment by frantisekz** [comment]
I guess it's because of fixing these => thesis in the backend.  You can try to change these-approval => thesis-approval for old applications or send a new one.

I've fixed the link for new emails. Thanks!

**Comment by dvolavko** [comment]
Ahoj, toto je tak naschvál? Že tam v podstate stále nemáš možnosť Deny/Approve.
![thesis approval - contact site admin](https://user-images.githubusercontent.com/30719674/31017741-e2a521c6-a529-11e7-9af5-0c65b2beda11.png)
