### ISSUE TITLE
Navigacia v sekciach

### ISSUE THREAD

**Issue by mhrusovs** [frantisekz/redhat-research#15]
Ked som napriklad v topicoch, nedokazem jednym rychlym pohladom zistit, kde som, bud musim pozerat na URL, alebo ist mysou nad ten vrchny panel.

Chcelo by to v kazdej sekcii napisat
Topics
Theses
Archive

Pripadne List of... ^

Vies si to predstavit? Mozeme to skusit ked tu budes.

**Comment by frantisekz** [comment]
Done
