### ISSUE TITLE
Home - text

### ISSUE THREAD

**Issue by mhrusovs** [frantisekz/redhat-research#16]
Greetings traveller!

Welcome to Red Hat’s thesis management system which lets you search through a list of available thesis topics for you to choose from. Have a topic in mind? Use the search engine, there’s a chance we already have what you're looking for!

[SEARCH BAR]

This portal consists of 4 main sections
TOPICS
These are open topics that you may apply for. You have the ability to contact the topic leader and discuss with them your application or a possible alteration of the topic.
THESES
A thesis is created once an application to a particular topic is confirmed by the leader. The original topic stays untouched or is hidden (depending on whether the leader is available to lead multiple instances of the same topic).
ARCHIVE
Once a thesis receives a grade (added by the leader after a successful defense), it is moved to archive.
UNIVERSITIES
Here you can find a list of universities that we are currently cooperating with. Is yours missing? Please contact us [mail to mhrusovs@redhat.com].

Na konci sa este pohrame s velkostou pisma a s rozhodenim textu.

**Comment by frantisekz** [comment]
Done
