### ISSUE TITLE
New Topic- Adding tags

### ISSUE THREAD

**Issue by mjedlick** [frantisekz/redhat-research#5]
Suggestions in search tags are slow, not user friendly, still loads where there are no suggetions
Navigation with arrows is weird - it lets you choose blank option
![image](https://user-images.githubusercontent.com/30621284/30541345-47e8584e-9c7b-11e7-8a60-9d1cf4db165d.png)

-just nice to have, maybe will work better on the actual page, where there are more tags saved

**Comment by frantisekz** [comment]
Slowness will be fixed by OpenShift v3, can't do anything about that right now.
