### ISSUE TITLE
/research.redhat.com/beta/diploma-thesis/

### ISSUE THREAD

**Issue by mjedlick** [frantisekz/redhat-research#6]
- tato stárnka mi přijde celá prostě... zvláštní 

1/ dá se na ní dostat jen z ikony, z položky v menu ne - tam to rovnou chce specifikovat jestli je to Topic, Theses...
2/ Students - Obviously :)
3/ Search - zvláštní vzhled a celé to na mě působí... takovým dojmem že to tam nepatří
4/ ale hlavně - když klidně na Search s prádným polem- ta to vyhodí jen několik těch projektů, hádám že ty nejnovější - dala bych ať to vyhodí všechny
5/ to hledání samo o sobě zrovna moc dobře nefunguje

**Comment by frantisekz** [comment]
Opraveno
