### ISSUE TITLE
Theses/ Topics

### ISSUE THREAD

**Issue by mjedlick** [frantisekz/redhat-research#7]
to je spíš taková technická otázka 

- mě jako nezasvěcenému není jasné co je co
- ty naše testovací topicy vyhazují obě dvě ty kategorie

**Comment by frantisekz** [comment]
Topic - téma k diplomce
Thesis - diplomka + student

Zakázal jsem zakládání Theses pro všechny uživatele - lze je vytvořit jen z linku v mailu, který dojde zadávajícím po přihlášení nějakého studenta. Takto vytvořené Theses se zobrazují správně.
