### ISSUE TITLE
Apply for this topic - žiadna zmena po výbere

### ISSUE THREAD

**Issue by dvolavko** [frantisekz/redhat-research#8]
Toto pravdepodobne nie je konkrétne chyba, ale bolo by fajn ak by sa niečo zmenilo po tom ako zvolíš Apply for this topic (napr. application sent/pending for approval?). Možno podobne pre Get in touch! (napr. your message was sent alebo niečo na ten štýl).

**Comment by frantisekz** [comment]
Opraveno, díky :)
