### ISSUE TITLE
Zapomenuté heslo

### ISSUE THREAD

**Issue by adarbuja** [frantisekz/redhat-research#9]
Když uživatel zapomene heslo, není schopen jej obnovit, resp. přijde mu takovýto e-mail: Someone requested that the password be reset for the following account: https://research.redhat.com/beta/ Username: agi_test If this was a mistake, just ignore this email and nothing will happen. To reset your password, visit the following address: 
A žádná adresa tam není.

**Comment by frantisekz** [comment]
Jo, je to rozbité jen na betě. Na research.redhat.com funguje bez problémů.
